### ISSUE TITLE
Trouble requiring module

### ISSUE THREAD

**Issue by vote539** [senotrusov/dejavu-fonts-ttf#1]
I can install this module just fine from npm.  However, Node doesn't seem to see it:

```
$ npm install dejavu-fonts-ttf
└── dejavu-fonts-ttf@2.35.5

$ node
> require("dejavu-fonts-ttf")
Error: Cannot find module 'dejavu-fonts-ttf'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
```

What I actually want to do is to get the path to the module so that I can reference the TTF files, but _require.resolve()_ doesn't work either.

```
$ node
> require.resolve("dejavu-fonts-ttf")
Error: Cannot find module 'dejavu-fonts-ttf'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
```

Any tips?

**Comment by vote539** [comment]
I figured it out; the _package.json_ file seems to need a "main" entrypoint in order for `require` to work.  I submitted a PR with a fix.

**Comment by senotrusov** [comment]
Thank you for your interest! Sorry it took me so long to reply.

I'm asking you to dedicate your contributions to the public domain. Please see the [Contributing Guidelines](https://github.com/senotrusov/dejavu-fonts-ttf/blob/master/CONTRIBUTING.md) for details on that. I added that file recently.

**Comment by senotrusov** [comment]
Sorry, I could not integrate this PR as there are no statement that this is a public domain contribution.
